version: "3.3"
services:
  web:
    image: "wputra/flasktest:latest"
    ports:
      - "5000:5000"
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: flask
      DB_PASSWORD: fl45k
      DB_NAME: urls
      FLASK_APP: main.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_APP_HOST: http://192.168.77.10:5000/
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
  redis_read:
    image: "redis:alpine"
    command: redis-server --slaveof redis 6379
    restart: always
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_DATABASE: urls
      MYSQL_USER: flask
      MYSQL_PASSWORD: fl45k

volumes:
  db_data: {}
